/**
 *
 * @file Dragon
 * @Labs.Wikibyte.org
 * @skin Wikibyte Dragon
 * @author Michael McCouman jr.
 * @copyright Copyright &copy; 2012 Michael McCouman jr.
 * @license Copyright (c) 2012 Michael McCouman jr.
 *
 */
<div id="wb-content"><?php if($this->data['loggedin']) { include ("docles.php"); echo '<center>'; echo '<img id="wb-doc-shadow" src="' .$SIpfad. '/images/docunder.png">'; echo '</center>'; }  ?> <a id="top"></a> <div id="mw-js-message" style="display:none;"<?php $this->html( 'userlangattributes' ) ?>></div> <div id="bodyContent"> <div class="row-fluid"> <div style="padding-left: 10px; margin-right: 10px;"> <?php if ( $this->data['isarticle'] ): ?> <div id="siteSub"><?php $this->msg( 'tagline' ) ?></div> <?php endif; ?><div id="contentSub"<?php $this->html( 'userlangattributes' ) ?>><?php $this->html( 'subtitle' ) ?></div> <?php if ( $this->data['undelete'] ): ?> <div id="contentSub2"><?php $this->html( 'undelete' ) ?></div> <?php endif; ?> <?php if( $this->data['newtalk'] ): ?><div class="usermessage"><img src="<?php echo $SImg; ?>/message.png"><?php $this->html( 'newtalk' ) ?></div> <?php endif; ?> <?php if ( $this->data['showjumplinks'] ): ?> <div id="jump-to-nav" class="mw-jump"> <?php $this->msg( 'jumpto' ) ?> <a href="#mw-head"><?php $this->msg( 'jumptonavigation' ) ?></a>, <a href="#p-search"><?php $this->msg( 'jumptosearch' ) ?></a> </div> <?php endif; ?><?php if ( $this->data['sitenotice'] ): ?> <?php $this->html( 'sitenotice' ) ?> <br> <?php endif; ?><?php $this->html( 'bodycontent' ) ?> <?php if ( $this->data['printfooter'] ): ?><div class="printfooter"><?php $this->html( 'printfooter' ); ?></div> </div> </div> <hr /> <div class="row-fluid"> <div class="span12"> <?php if($this->data['loggedin']) { echo '<ul class="tabs left">'; echo ' <li><a href="#tabr1">Kategorisiert</a></li>'; echo ' <li><a href="#tabr2">Letzter Admin</a></li>'; echo '</ul>'; echo '<div id="tabr1" class="tab-content">'; } ?> <div style="padding-left:10px; font-size:14px; float:left"> <?php endif; ?> <?php if ( $this->data['catlinks'] ): ?> <?php $this->html( 'catlinks' ); ?> <?php endif; ?> </div> <?php echo '<a style="float:right;" href="http://flattr.com/thing/785099/Wikibyte-Network-and-Labs" target="_blank"><img src="http://api.flattr.com/button/flattr-badge-large.png" alt="Flattr und unterst�tzen" title="Flattr this" border="0" /></a>'; ?> <?php if($this->data['loggedin']) { ?> </div> <div id="tabr2" class="tab-content"> <?php echo '<pre>'. $wgTitle->getArticle(). '</pre><br>';  include ("/webserver/wikibyte.org/Wikis/-/w/skins/dragon/Site/avatarMini.php"); ?> </div> <?php } ?> <?php if ( $this->data['dataAfterContent'] ): ?> <<?php $this->html( 'dataAfterContent' ); ?> <<?php endif; ?> <div class="visualClear"></div> <?php $this->html( 'debughtml' ); ?> </div> </div> </div> </div>
