<style type="text/css">
<?php 
####################################################### STANDARD ########################################################## 
/**
 * Dragon Skin v2
 * by Michael McCouman jr
 * Copyright 2012 Wikibyte.org
 * MediaWiki Skin
 */


function parse (dragoncss-skining) {

if $puting_dragon_style_design !== $skinblog || $dragon_skin['blog'] {

	$dragon_skin = "
.navbar-spezial .navbar-inner {
	background-color: #1b1b1b;
	background-image: -moz-linear-gradient(top, #88CCEE, #0088FF);
	background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#88CCEE), to(#0088FF));
	background-image: -webkit-linear-gradient(top, #88CCEE, #0088FF);
	background-image: -o-linear-gradient(top, #88CCEE, #0088FF);
	background-image: linear-gradient(to bottom, #88CCEE, #0088FF);
	background-repeat: repeat-x;
	border-color: #252525;
	filter: progid:dximagetransform.microsoft.gradient(startColorstr='#ff88CCEE', endColorstr='#ff0088FF', GradientType=0);
}
.navbar .divider-verticala-spezial {
	height: 40px;
	margin: 0;
	border-right: 1px solid #8CF;
	border-left:  1px solid #06A;
}
.navbar .nav > li > a.a-spezial {
	color: #fff;
	text-shadow: 0 1px 0 #08c;
	float: none;
	padding: 10px 15px 10px;
	text-decoration: none;
}
.navbar .nav > li.dropdown.open > a.a-spezial:focus,
.navbar .nav > li.dropdown.open > a.a-spezial:hover {
	color: #000;
	text-decoration: none;
	background-color: transparent;
}
.navbar .nav > li.dropdown.open {
	color: #000;
	text-decoration: none;
	background-color: #e5e5e5;
	-webkit-box-shadow: inset 0 3px 8px rgba(0, 0, 0, 0.125);
		-moz-box-shadow: inset 0 3px 8px rgba(0, 0, 0, 0.125);
			box-shadow: inset 0 3px 8px rgba(0, 0, 0, 0.125);
}
.navbar .nav > li.dropdown.open a:hover{
	color: #000;
	text-decoration: none;
	background-color: transparent;
}";
	} 
	return $dragon_skin['blog'];
} else {
echo "<!-- the skin is stab. to out as ".$skinblog_mas." -->";
}
##### end stab skiningbloger
}
?>
</style>